jobs:
  'Tests':

    run-on:
    - type: branch
      include-match: ^.*$

    context:

      task-defaults:
        max-auto-trials: 1
        traits:
          nodejs: true
        scripts:
          'npm_install':
            body: 'npm install'
        trial-attachments:
          logs:
            glob: spec/log*.txt
            content-type: text/plain
          logs_html:
            glob: spec/log*.html
            content-type: text/html

      tasks:
        unit:
          name: 'JS Tests'
          scripts:
            'model_tests':
              name: 'Model Tests'
              body: 'npm -s run model-tests | tee spec/log.txt'
              start-when:
              - script: 'npm_install'
            'format_tap':
              body: 'cat spec/log.txt | npm run -s tap-spec -- --color | npm run -s coffee spec/_format-summary.coffee > spec/log.html'
              start-when:
              - script: 'model_tests'
